version: '3'

services:

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: web
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    links:
      - php
    networks: 
        mynetwork:
          ipv4_address: 10.6.0.2

   
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - .:/app/
    links:
      - mysql
    networks: 
        mynetwork:
          ipv4_address: 10.6.0.20
    
   
  mysql:
    build: 
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: mysql
    environment: 
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
    networks: 
        mynetwork:
          ipv4_address: 10.6.0.4
 
  
  myadmin:
        image: phpmyadmin
        ports:
              - "8000:80"
        container_name: phpmyadmin
        environment:
            PMA_USER: root
            PMA_PASSWORD: toor
            PMA_HOST: mysql
        links:
            - mysql:db
        networks: 
          mynetwork:
           ipv4_address: 10.6.0.10

networks: 
  mynetwork:
    driver: bridge
    ipam:
      config: 
        - subnet: 10.6.0.0/16